
# this file is available in this path cd ~/.kube/config in management server

apiVersion: v1
clusters:
  - cluster:
      certificate-authority-data: XXXXXXXXXXX
      server: https://api.harinadh.xyz
      tls-server-name: api.internal.harinadh.xyz
    name: harinadh.xyz
contexts:
  - context:
      cluster: harinadh.xyz
      namespace: development
      user: user1
    name: user1-context
current-context: user1-context
kind: Config
users:
  - name: user1
    user:
      client-certificate: /root/useer1.crt
      client-key: /root/user1.key
---
# USER 1

apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUMrRENDQWVDZ0F3SUJBZ0lNR0ZDazBObFJpcmpPSGttTU1BMEdDU3FHU0liM0RRRUJDd1VBTUJneEZqQVUKQmdOVkJBTVREV3QxWW1WeWJtVjBaWE10WTJFd0hoY05NalV3TnpBM01UY3hOelV6V2hjTk16VXdOekEzTVRjeApOelV6V2pBWU1SWXdGQVlEVlFRREV3MXJkV0psY201bGRHVnpMV05oTUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGCkFBT0NBUThBTUlJQkNnS0NBUUVBdnY1NHE0RXI1UTJ3TS9XTHlucUViL243K2VBdVVNdm91ZWkwMU1iaGlZZ2UKQTRCK1lHVFFSQVJrTlhsOTY0bDE0KzlacU5WMmIwYm42VFVsYWw1NzB1RTBUSVJYNjhwMHdrenpFa3V2ZWltRwo0VDkvRmUxUWEvbzBjYnRnQVBYczd4TjZHZnkxM1k5RWU2aHp5Yms3Qm1UTHE4ZzdIUWY3ZVE1ZkUwOXF1Yll4ClNYQUR0OG8zZ2RYd3VrdERJMUQ0RlFtSVRMOER1M1g1MTdIQ1dVTGtUODhKTzdjRi9YcWZ5ejNpcXBkYXhsV3MKdXdhdXprSkh5VTd6Nk1BSzhIWWRiak5ONzFiMXJxUEZlbzFWZ0J6Z2Fua0h2OXF3Q21JNGxuemovOTRGTEF2MApDM1F5a05ES2V1bnVqUFRTa0dsSHc4eGxRakdXeUs1M2VuSnN4SG9iWXdJREFRQUJvMEl3UURBT0JnTlZIUThCCkFmOEVCQU1DQVFZd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBZEJnTlZIUTRFRmdRVXFWNHVFcUZmS0lQYWx5b1YKNUxrQ1B6eHRDakF3RFFZSktvWklodmNOQVFFTEJRQURnZ0VCQUErdFdRdzQ3S2hQMlFQUDNjWWVQMFhCNjRINwpES0N1c1I4eDdKdDhwdU9oRnBkTDE3bUU1QjBjaEcyY1pubENOc1F6SXlLUXZLTk5ON0JvSjFySHBlekZnT1V0CnMzdWlQSitsNTdYMjQxYWhSQmFNSEFqdnpmNTUwdmpGT1R1V1owUFpFSGlreHVHZjA5NmwxV0pVb2g2OVp6dDEKbG5iT2ZrY09HSzRmdGlUQTJjb0tTMTZiUmJmbjhRM2t4L2t5Vi9STm44MTlGRnR4K21LM2NrQjBNSHNSMHZ3cwpkNHVVUEVpcitISnVEODRReG9GTmUzQTdPcXdnU3dzanMzTGFmTTBuWit2aHNCazdscVE1MUdvQms4L1JDZHdGCnZweXpOblNQYXpYMk5GdDBGQTlIQnJnbWRUeWlMcVh2cTlhUHc2RnBhZHN1UkhJT2hXNUgwNFlCSmpJPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    server: https://api.harinadh.xyz
    tls-server-name: api.internal.harinadh.xyz
  name: harinadh.xyz
contexts:
- context:
    cluster: harinadh.xyz
    namespace: development
    user: user1
  name: user1-context
current-context: user1-context
kind: Config
users:
- name: user1
  user:
    client-certificate-data: /root/useer1.crt
    client-key-data: /root/user1.key

---

# USER2  remove data at the end in client-certificate and client-key


apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUMrRENDQWVDZ0F3SUJBZ0lNR0ZDazBObFJpcmpPSGttTU1BMEdDU3FHU0liM0RRRUJDd1VBTUJneEZqQVUKQmdOVkJBTVREV3QxWW1WeWJtVjBaWE10WTJFd0hoY05NalV3TnpBM01UY3hOelV6V2hjTk16VXdOekEzTVRjeApOelV6V2pBWU1SWXdGQVlEVlFRREV3MXJkV0psY201bGRHVnpMV05oTUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGCkFBT0NBUThBTUlJQkNnS0NBUUVBdnY1NHE0RXI1UTJ3TS9XTHlucUViL243K2VBdVVNdm91ZWkwMU1iaGlZZ2UKQTRCK1lHVFFSQVJrTlhsOTY0bDE0KzlacU5WMmIwYm42VFVsYWw1NzB1RTBUSVJYNjhwMHdrenpFa3V2ZWltRwo0VDkvRmUxUWEvbzBjYnRnQVBYczd4TjZHZnkxM1k5RWU2aHp5Yms3Qm1UTHE4ZzdIUWY3ZVE1ZkUwOXF1Yll4ClNYQUR0OG8zZ2RYd3VrdERJMUQ0RlFtSVRMOER1M1g1MTdIQ1dVTGtUODhKTzdjRi9YcWZ5ejNpcXBkYXhsV3MKdXdhdXprSkh5VTd6Nk1BSzhIWWRiak5ONzFiMXJxUEZlbzFWZ0J6Z2Fua0h2OXF3Q21JNGxuemovOTRGTEF2MApDM1F5a05ES2V1bnVqUFRTa0dsSHc4eGxRakdXeUs1M2VuSnN4SG9iWXdJREFRQUJvMEl3UURBT0JnTlZIUThCCkFmOEVCQU1DQVFZd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBZEJnTlZIUTRFRmdRVXFWNHVFcUZmS0lQYWx5b1YKNUxrQ1B6eHRDakF3RFFZSktvWklodmNOQVFFTEJRQURnZ0VCQUErdFdRdzQ3S2hQMlFQUDNjWWVQMFhCNjRINwpES0N1c1I4eDdKdDhwdU9oRnBkTDE3bUU1QjBjaEcyY1pubENOc1F6SXlLUXZLTk5ON0JvSjFySHBlekZnT1V0CnMzdWlQSitsNTdYMjQxYWhSQmFNSEFqdnpmNTUwdmpGT1R1V1owUFpFSGlreHVHZjA5NmwxV0pVb2g2OVp6dDEKbG5iT2ZrY09HSzRmdGlUQTJjb0tTMTZiUmJmbjhRM2t4L2t5Vi9STm44MTlGRnR4K21LM2NrQjBNSHNSMHZ3cwpkNHVVUEVpcitISnVEODRReG9GTmUzQTdPcXdnU3dzanMzTGFmTTBuWit2aHNCazdscVE1MUdvQms4L1JDZHdGCnZweXpOblNQYXpYMk5GdDBGQTlIQnJnbWRUeWlMcVh2cTlhUHc2RnBhZHN1UkhJT2hXNUgwNFlCSmpJPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    server: https://api.harinadh.xyz
    tls-server-name: api.internal.harinadh.xyz
  name: harinadh.xyz
contexts:
- context:
    cluster: harinadh.xyz
    namespace: production
    user: user2
  name: user2-context
current-context: user2-context
kind: Config
users:
- name: user2
  user:
    client-certificate: /root/user2.crt
    client-key: /root/user2.key


# paste these users in control plane like below


vi USER1-CONFIG (paste the user1 data)
export KUBECONFIG=/root/USER1-CONFIG
kubectl get pods (you'll get forbidden error in development ns)


vi USER2-CONFIG (paste the user2 data)
export KUBECONFIG=/root/USER2-CONFIG
kubectl get pods (you'll get forbidden error in production ns)



# we have to create role for both users and deploy 

---

# configfile for admin

apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUMrRENDQWVDZ0F3SUJBZ0lNR0ZDazBObFJpcmpPSGttTU1BMEdDU3FHU0liM0RRRUJDd1VBTUJneEZqQVUKQmdOVkJBTVREV3QxWW1WeWJtVjBaWE10WTJFd0hoY05NalV3TnpBM01UY3hOelV6V2hjTk16VXdOekEzTVRjeApOelV6V2pBWU1SWXdGQVlEVlFRREV3MXJkV0psY201bGRHVnpMV05oTUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGCkFBT0NBUThBTUlJQkNnS0NBUUVBdnY1NHE0RXI1UTJ3TS9XTHlucUViL243K2VBdVVNdm91ZWkwMU1iaGlZZ2UKQTRCK1lHVFFSQVJrTlhsOTY0bDE0KzlacU5WMmIwYm42VFVsYWw1NzB1RTBUSVJYNjhwMHdrenpFa3V2ZWltRwo0VDkvRmUxUWEvbzBjYnRnQVBYczd4TjZHZnkxM1k5RWU2aHp5Yms3Qm1UTHE4ZzdIUWY3ZVE1ZkUwOXF1Yll4ClNYQUR0OG8zZ2RYd3VrdERJMUQ0RlFtSVRMOER1M1g1MTdIQ1dVTGtUODhKTzdjRi9YcWZ5ejNpcXBkYXhsV3MKdXdhdXprSkh5VTd6Nk1BSzhIWWRiak5ONzFiMXJxUEZlbzFWZ0J6Z2Fua0h2OXF3Q21JNGxuemovOTRGTEF2MApDM1F5a05ES2V1bnVqUFRTa0dsSHc4eGxRakdXeUs1M2VuSnN4SG9iWXdJREFRQUJvMEl3UURBT0JnTlZIUThCCkFmOEVCQU1DQVFZd0R3WURWUjBUQVFIL0JBVXdBd0VCL3pBZEJnTlZIUTRFRmdRVXFWNHVFcUZmS0lQYWx5b1YKNUxrQ1B6eHRDakF3RFFZSktvWklodmNOQVFFTEJRQURnZ0VCQUErdFdRdzQ3S2hQMlFQUDNjWWVQMFhCNjRINwpES0N1c1I4eDdKdDhwdU9oRnBkTDE3bUU1QjBjaEcyY1pubENOc1F6SXlLUXZLTk5ON0JvSjFySHBlekZnT1V0CnMzdWlQSitsNTdYMjQxYWhSQmFNSEFqdnpmNTUwdmpGT1R1V1owUFpFSGlreHVHZjA5NmwxV0pVb2g2OVp6dDEKbG5iT2ZrY09HSzRmdGlUQTJjb0tTMTZiUmJmbjhRM2t4L2t5Vi9STm44MTlGRnR4K21LM2NrQjBNSHNSMHZ3cwpkNHVVUEVpcitISnVEODRReG9GTmUzQTdPcXdnU3dzanMzTGFmTTBuWit2aHNCazdscVE1MUdvQms4L1JDZHdGCnZweXpOblNQYXpYMk5GdDBGQTlIQnJnbWRUeWlMcVh2cTlhUHc2RnBhZHN1UkhJT2hXNUgwNFlCSmpJPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    server: https://api.harinadh.xyz
    tls-server-name: api.internal.harinadh.xyz
  name: harinadh.xyz
contexts:
- context:
    cluster: harinadh.xyz
    user: sai
  name: sai-context
current-context: sai-context
kind: Config
users:
- name: sai
  user:
    client-certificate: /root/sai.crt
    client-key: /root/sai.key






